# Generated by Django 2.1.4 on 2019-01-01 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botModel', models.CharField(max_length=50)),
                ('botName', models.CharField(max_length=50, null=True)),
                ('botOwner', models.CharField(max_length=100, null=True)),
                ('localization', models.CharField(choices=[('loc', 'Local'), ('rem', 'Remote')], default='Loc', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Controler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ControlerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('maxDigitalPins', models.PositiveIntegerField()),
                ('maxAnalogPins', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('pinNum', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='undefined', max_length=50)),
                ('address', models.CharField(default='undefined', max_length=50)),
                ('code', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='undefined', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBot.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='PowerLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(default='service', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lin', 'Linéaire'), ('ang', 'Angulaire')], default='ang', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeInSec', models.PositiveIntegerField()),
                ('rotInDeg', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myBot.Device')),
                ('closeLevel', models.CharField(choices=[('Low', 'Niveau bas'), ('High', 'Niveau haut')], default='Low', max_length=5)),
            ],
            bases=('myBot.device',),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myBot.Device')),
                ('mesureUnit', models.CharField(max_length=20)),
            ],
            bases=('myBot.device',),
        ),
        migrations.CreateModel(
            name='Servo',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myBot.Device')),
                ('rev', models.BooleanField()),
                ('toggle', models.BooleanField()),
                ('min', models.PositiveIntegerField(default=0)),
                ('max', models.PositiveIntegerField(default=180)),
                ('servoType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myBot.ServoType')),
                ('speedClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myBot.SpeedClass')),
            ],
            bases=('myBot.device',),
        ),
        migrations.AddField(
            model_name='interface',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myBot.Link'),
        ),
        migrations.AddField(
            model_name='device',
            name='controler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBot.Controler'),
        ),
        migrations.AddField(
            model_name='controler',
            name='controlerType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myBot.ControlerType'),
        ),
        migrations.AddField(
            model_name='controler',
            name='interface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myBot.Interface'),
        ),
        migrations.AddField(
            model_name='controler',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBot.Part'),
        ),
    ]
