# Generated by Django 2.1.4 on 2019-01-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myBot.Part'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='botModel',
            field=models.CharField(max_length=50, verbose_name='modèle'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='botName',
            field=models.CharField(max_length=50, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='botOwner',
            field=models.CharField(max_length=100, null=True, verbose_name='propriétaire'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='localization',
            field=models.CharField(choices=[('loc', 'Local'), ('rem', 'Remote')], default='Loc', help_text='Local : le Bot est sur la même machine que le système ', max_length=20, verbose_name='localisation'),
        ),
        migrations.AlterField(
            model_name='controler',
            name='title',
            field=models.CharField(max_length=50, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='device',
            name='title',
            field=models.CharField(max_length=50, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='function',
            name='title',
            field=models.CharField(max_length=50, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='title',
            field=models.CharField(default='undefined', max_length=50, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='part',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBot.Bot', verbose_name='bot'),
        ),
        migrations.AlterField(
            model_name='part',
            name='title',
            field=models.CharField(max_length=50, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='powerline',
            name='title',
            field=models.CharField(max_length=50, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50, verbose_name='intitulé'),
        ),
    ]
