# Generated by Django 2.1.4 on 2019-01-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='intitulé')),
            ],
        ),
        migrations.RemoveField(
            model_name='controler',
            name='address',
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('interface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myBot.Interface')),
                ('port', models.CharField(max_length=100, verbose_name='nom du port')),
                ('baudrate', models.CharField(choices=[('9600', '9600'), ('19200', '19200'), ('57600', '57600'), ('115200', '115200')], max_length=10)),
            ],
            bases=('myBot.interface',),
        ),
    ]
