# Generated by Django 2.1.4 on 2019-01-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='link',
        ),
        migrations.AlterField(
            model_name='controler',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='controler',
            name='interface',
            field=models.CharField(choices=[('usb', 'USB-Serial'), ('ip-eth', 'IP on Ethernet'), ('ip-wifi', 'IP on Wifi')], default='usb', max_length=10, verbose_name="type d'interface"),
        ),
        migrations.DeleteModel(
            name='Interface',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
