# Generated by Django 2.1.4 on 2019-01-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBot', '0002_auto_20190104_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='controler',
            name='address',
            field=models.CharField(help_text='paste or select', max_length=50, null=True, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='device',
            name='pinNum',
            field=models.PositiveIntegerField(blank=True, help_text='donné à titre indicatif', null=True, verbose_name='n° de broche'),
        ),
        migrations.AlterField(
            model_name='device',
            name='prefix',
            field=models.CharField(default='undefined', help_text="utilisé dans l'adressage du device", max_length=10, null=True, verbose_name="préfixe pour l'adressage"),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='mesureUnit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servo',
            name='max',
            field=models.PositiveIntegerField(default=180, help_text='en action, le servo ne pourra pas aller au-dessus de cette valeur', verbose_name='valeur maximale'),
        ),
        migrations.AlterField(
            model_name='servo',
            name='min',
            field=models.PositiveIntegerField(default=0, help_text='en action, le servo ne pourra pas aller sous cette valeur', verbose_name='valeur minimale'),
        ),
    ]
