# Generated by Django 2.1.4 on 2019-01-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBot', '0002_auto_20190120_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='bytesize',
            field=models.CharField(choices=[('FIVEBITS', '5'), ('SIXBITS', '6'), ('SEVENBITS', '7'), ('EIGHTBITS', '8')], default='8', max_length=100),
        ),
        migrations.AlterField(
            model_name='serial',
            name='baudrate',
            field=models.CharField(choices=[('9600', '9600'), ('19200', '19200'), ('57600', '57600'), ('115200', '115200')], default='115200', max_length=10),
        ),
        migrations.AlterField(
            model_name='serial',
            name='port',
            field=models.CharField(max_length=100, verbose_name="nom de l'interface"),
        ),
    ]
