# Generated by Django 2.1.4 on 2019-01-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBot', '0003_auto_20190105_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='servo',
            name='model',
            field=models.CharField(default='standard', max_length=20, verbose_name='marque ou modèle'),
        ),
    ]
