# Generated by Django 2.1.4 on 2019-01-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBot', '0003_auto_20190120_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='parity',
            field=models.CharField(choices=[('PARITY_NONE', 'None'), ('PARITY_EVEN', 'Even'), ('PARITY_ODD', 'Odd'), ('PARITY_MARK', 'Mark'), ('PARITY_SPACE', 'Space')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='serial',
            name='stopbits',
            field=models.CharField(choices=[('STOPBITS_ONE', '1'), ('STOPBITS_ONE_POINT_FIVE', '1,5'), ('STOPBITS_TWO', '2')], default='1', max_length=20, verbose_name='bits de stop'),
        ),
        migrations.AddField(
            model_name='serial',
            name='timeout',
            field=models.CharField(default='None', help_text='None : on attend sans limite jusquà la réception du nb de bytes / 0 : mode non bloquant / x : valeur en secondes sauf si tous les bytes sont reçus', max_length=20, verbose_name="délai d'attente"),
        ),
        migrations.AddField(
            model_name='serial',
            name='xonxoff',
            field=models.BooleanField(default=False, verbose_name='enable software flow control'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='baudrate',
            field=models.CharField(choices=[('9600', '9600'), ('19200', '19200'), ('57600', '57600'), ('115200', '115200')], default='115200', max_length=10, verbose_name='débit (baudrate)'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='bytesize',
            field=models.CharField(choices=[('FIVEBITS', '5'), ('SIXBITS', '6'), ('SEVENBITS', '7'), ('EIGHTBITS', '8')], default='8', max_length=100, verbose_name='octets de données (bytesize)'),
        ),
    ]
