# Generated by Django 2.1.4 on 2019-01-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBot', '0004_servo_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servo',
            name='model',
        ),
        migrations.RemoveField(
            model_name='servo',
            name='speedClass',
        ),
        migrations.AddField(
            model_name='powerline',
            name='maxCurrent',
            field=models.DecimalField(decimal_places=1, default=0, help_text='unité = A', max_digits=5, null=True, verbose_name='courant maximal prévu'),
        ),
        migrations.AddField(
            model_name='servotype',
            name='model',
            field=models.CharField(max_length=20, null=True, verbose_name='marque ou modèle (ou standard)'),
        ),
        migrations.AddField(
            model_name='servotype',
            name='speedClass',
            field=models.ForeignKey(help_text='la classe de vitesse est indispensable pour moduler la vitesse du servo', null=True, on_delete=django.db.models.deletion.CASCADE, to='myBot.SpeedClass', verbose_name='classe de vitesse'),
        ),
        migrations.AlterField(
            model_name='device',
            name='controler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myBot.Controler', verbose_name='contrôleur de rattachement'),
        ),
        migrations.AlterField(
            model_name='device',
            name='prefix',
            field=models.CharField(help_text="utilisé dans l'adressage du device", max_length=10, null=True, verbose_name="préfixe pour l'adressage"),
        ),
        migrations.AlterField(
            model_name='relay',
            name='closeLevel',
            field=models.CharField(choices=[('Low', 'Niveau bas'), ('High', 'Niveau haut')], default='Low', help_text='précise le niveau à donner à la broche pour fermer le relais', max_length=5, verbose_name='niveau fermé'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='mesureUnit',
            field=models.CharField(max_length=20, null=True, verbose_name='unité de mesure'),
        ),
        migrations.AlterField(
            model_name='servo',
            name='servoType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myBot.ServoType', verbose_name='type de servo'),
        ),
        migrations.AlterField(
            model_name='speedclass',
            name='rotInDeg',
            field=models.PositiveIntegerField(verbose_name='rotation en degrés'),
        ),
        migrations.AlterField(
            model_name='speedclass',
            name='timeInSec',
            field=models.PositiveIntegerField(verbose_name='temps en secondes'),
        ),
    ]
