# Generated by Django 2.1.4 on 2019-01-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBot', '0005_auto_20190113_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedclass',
            name='rotInDeg',
        ),
        migrations.AddField(
            model_name='speedclass',
            name='move',
            field=models.PositiveIntegerField(null=True, verbose_name='mouvement'),
        ),
        migrations.AddField(
            model_name='speedclass',
            name='unit',
            field=models.CharField(max_length=20, null=True, verbose_name='unité de mouvement'),
        ),
    ]
