# Generated by Django 2.1.4 on 2019-01-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBot', '0006_auto_20190113_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedclass',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speedclass',
            name='move',
            field=models.PositiveIntegerField(null=True, verbose_name='valeur du mouvement'),
        ),
    ]
