# Generated by Django 2.1.4 on 2019-01-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBot', '0007_auto_20190113_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
