from django.contrib import admin
from myBot.models import Bot,Part,Controler,Servo,ServoType,SpeedClass,Sensor,Relay,PowerLine,Function,Service,ControlerType,Interface,Link
admin.site.register(Bot)
admin.site.register(Part)
admin.site.register(Controler)
admin.site.register(Servo)
admin.site.register(ServoType)
admin.site.register(SpeedClass)
admin.site.register(Sensor)
admin.site.register(Relay)
admin.site.register(PowerLine)
admin.site.register(Function)
admin.site.register(Service)
admin.site.register(ControlerType)
admin.site.register(Interface)
admin.site.register(Link)
